# Generated by Django 5.0.6 on 2024-06-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
